### ISSUE TITLE
Why purse is not yet published on PyPI?

### ISSUE THREAD

**Issue by elbowz** [plataux/purse#2]
I'm using your great lib in a my [project](https://github.com/elbowz/PyMAPE)...

I would like release it on PyPI, but I have just discovered that the dependencies cannot point to a github repository, but I must point to something already published on PyPI.

I see that you have done all the works (eg. poetry, run.sh) but I cannot find purse on PyPI, or at least not YOUR purse lib (but an [namesake lib](https://pypi.org/project/purse/)).

Could you publish it...this can really help me :)

Thanks for your works!

**Comment by mk-mahfouz** [comment]
hey @elbowz,

looks like a very interesting project you are working on, will definitely spend sometime over it.
sure, I haven't seen any major issues or anything, so it may be time to publish it to make it easier to install.

Thank you for bringing this up!

**Comment by mk-mahfouz** [comment]
will probably just call it "redis-purse"

**Comment by elbowz** [comment]
Thanks to you for your speedy answer and the oncoming package publishing...really appreciated!

> will probably just call it "redis-purse"

Yeah, I think is perfect and you can also leave the same library name (ie.` import purse`)

..and for what I see, from 8b77132eaf16e78216c76386785773adfc63570c, "redis-purse" is the original name ;)

**Comment by mk-mahfouz** [comment]
I couldn't use ``purse`` because as you said the name was already taken :)

I dunno...

It should already be up as redis-purse now with ``pip install``, enjoy !
