### ISSUE TITLE
Use official Redis in place of AioRedis

### ISSUE THREAD

**Issue by bratao** [plataux/purse#3]
The Aioredis is discontinued and now is integrated in the official Python redis.

**Comment by mk-mahfouz** [comment]
yea, realized this a few weeks ago, and trying to figure out if it is really, really, truly a drop in replacement. I mean whether or not it is, it will need to be dealt with.

But thanks for the heads up! Will work on it.

**Comment by mk-mahfouz** [comment]
@bratao updates have been made. Thanks for driving this.
